version: "3.9"

services:

  migrate:
    image: reg-devdew.chub-beta.ts.net/pos-app:latest
    container_name: pos-migrate
    command: ["dotnet", "POS.dll", "migrate"]
    volumes:
      - pos-db:/app/data
    networks:
      - app-net
    restart: "no"

  pos-app:
    image: reg-devdew.chub-beta.ts.net/pos-app:latest
    container_name: pos-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "5000:80"
    restart: unless-stopped
    volumes:
      - pos-db:/app/data
    networks:
      - app-net
    environment:
      ASPNETCORE_ENVIRONMENT: Production

networks:
  app-net:
    name: app-net
    driver: bridge

volumes:
  pos-db:
    name: pos-db