steps:
  build:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - echo "Running Build Stage"
      - dotnet restore POS/POS.csproj
      - dotnet build POS/POS.csproj --configuration Release --no-restore
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "build" || STAGE == "all" || STAGE == "push"

  test:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    depends_on: [ build ]
    commands:
      - echo "Running Test Stage"
      - dotnet test POS/POS.csproj --configuration Release --no-build
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "test" || STAGE == "all"

  docker:
    image: docker:24
    depends_on: [ build ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Logging into registry"
      - echo "$DOCKER_PASSWORD" | docker login reg-devdew.chub-beta.ts.net -u "$DOCKER_USERNAME" --password-stdin
      - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
      - docker build -t reg-devdew.chub-beta.ts.net/pos-app:$SHORT_SHA -f Dockerfile .
      - docker push reg-devdew.chub-beta.ts.net/pos-app:$SHORT_SHA
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "push" || STAGE == "all"