steps:
  build:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - echo "Running Build Stage"
      - dotnet restore POS/POS.csproj
      - dotnet build POS/POS.csproj --configuration Release --no-restore
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "build" || STAGE == "all" || STAGE == "push"

  test:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    depends_on: [ build ]
    commands:
      - echo "Running Test Stage"
      - dotnet test POS/POS.csproj --configuration Release --no-build
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "test" || STAGE == "all"

  docker:
    image: woodpeckerci/plugin-docker-buildx
    depends_on: [ build ]
    settings:
      repo: reg-devdew.chub-beta.ts.net/pos-app
      registry: reg-devdew.chub-beta.ts.ne
      dockerfile: Dockerfile
      tags:
        - ${CI_COMMIT_SHA:0:7}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true
    when:
      - event: push
        evaluate: CI_COMMIT_BRANCH == "master"
      - event: manual
        evaluate: STAGE == "push" || STAGE == "all"